version: '3.3'

services:
  flask:
    build: ./api
    container_name: flask
    restart: always
    env_file:
      - ./api/app.env
    depends_on:
      - database
    expose:
      - 8000
    volumes:
      - ./api:/app

  database:
    image: postgres:12.3-alpine
    container_name: postgres
    restart: always
    env_file: postgres.env
    expose:
      - 5432

  vue:
    build: ./app
    container_name: vue
    restart: always
    depends_on:
      - flask
    expose:
      - 8080
    volumes:
      - ./app:/app

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - 80:80
