"""empty message

Revision ID: f4597fdadb2e
Revises: 6db4d8983f8c
Create Date: 2020-06-06 08:56:36.739283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4597fdadb2e'
down_revision = '6db4d8983f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
